run: BBTest
	./BBTest
BBTest: BBTest.cpp
	g++ -o BBTest BBTest.cpp `pkg-config opencv --cflags --libs`
TemplMatch: TemplMatch.cpp
	g++ -o TemplMatch TemplMatch.cpp `pkg-config opencv --cflags --libs`
