/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bubblebot.jni;

import com.opencv.jni.image_pool;// import the image_pool interface for playing nice with
								 // android-opencv

/** Feedback - provide visual feedback on images
*/
public class Feedback {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public Feedback(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(Feedback obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      bubblebotJNI.delete_Feedback(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Feedback() {
    this(bubblebotJNI.new_Feedback(), true);
  }

  public void ResetScore() {
    bubblebotJNI.Feedback_ResetScore(swigCPtr, this);
  }

  public int DetectOutline(int idx, image_pool pool, double thres1, double thres2) {
    return bubblebotJNI.Feedback_DetectOutline(swigCPtr, this, idx, image_pool.getCPtr(pool), pool, thres1, thres2);
  }

  public void drawText(int i, image_pool pool, String ctext, int row, int hJust, SWIGTYPE_p_Scalar color, double fontScale, double thickness) {
    bubblebotJNI.Feedback_drawText__SWIG_0(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext, row, hJust, SWIGTYPE_p_Scalar.getCPtr(color), fontScale, thickness);
  }

  public void drawText(int i, image_pool pool, String ctext, int row, int hJust, SWIGTYPE_p_Scalar color, double fontScale) {
    bubblebotJNI.Feedback_drawText__SWIG_1(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext, row, hJust, SWIGTYPE_p_Scalar.getCPtr(color), fontScale);
  }

  public void drawText(int i, image_pool pool, String ctext, int row, int hJust, SWIGTYPE_p_Scalar color) {
    bubblebotJNI.Feedback_drawText__SWIG_2(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext, row, hJust, SWIGTYPE_p_Scalar.getCPtr(color));
  }

  public void drawText(int i, image_pool pool, String ctext, int row, int hJust) {
    bubblebotJNI.Feedback_drawText__SWIG_3(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext, row, hJust);
  }

  public void drawText(int i, image_pool pool, String ctext, int row) {
    bubblebotJNI.Feedback_drawText__SWIG_4(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext, row);
  }

  public void drawText(int i, image_pool pool, String ctext) {
    bubblebotJNI.Feedback_drawText__SWIG_5(swigCPtr, this, i, image_pool.getCPtr(pool), pool, ctext);
  }

}
