/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bubblebot.jni;


/** MarkupForm - for marking up form
*/
public class MarkupForm {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public MarkupForm(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(MarkupForm obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bubblebotJNI.delete_MarkupForm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean outputFieldCounts(String bubbleVals, String outputPath) {
    return bubblebotJNI.MarkupForm_outputFieldCounts(swigCPtr, this, bubbleVals, outputPath);
  }

  public boolean markupForm(String markupPath, String formPath, String outputPath) {
    return bubblebotJNI.MarkupForm_markupForm(swigCPtr, this, markupPath, formPath, outputPath);
  }

  public MarkupForm() {
    this(bubblebotJNI.new_MarkupForm(), true);
  }

}
