/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bubblebot.jni;


/** Processor - for processing images that are stored in an image pool
*/
public class Processor {
  private long swigCPtr;
  protected boolean swigCMemOwn;
  public Processor(long cPtr, boolean cMemoryOwn) {
	swigCMemOwn = cMemoryOwn;
	swigCPtr = cPtr;
  }
  public static long getCPtr(Processor obj) {
	return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bubblebotJNI.delete_Processor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Processor() {
    this(bubblebotJNI.new_Processor(), true);
  }

  public boolean loadTemplate(String templatePath) {
    return bubblebotJNI.Processor_loadTemplate(swigCPtr, this, templatePath);
  }

  public boolean trainClassifier(String trainingImageDir) {
    return bubblebotJNI.Processor_trainClassifier(swigCPtr, this, trainingImageDir);
  }

  public boolean loadForm(String imagePath, int rotate90) {
    return bubblebotJNI.Processor_loadForm__SWIG_0(swigCPtr, this, imagePath, rotate90);
  }

  public boolean loadForm(String imagePath) {
    return bubblebotJNI.Processor_loadForm__SWIG_1(swigCPtr, this, imagePath);
  }

  public boolean alignForm(String alignedImageOutputPath) {
    return bubblebotJNI.Processor_alignForm(swigCPtr, this, alignedImageOutputPath);
  }

  public boolean processForm(String outPath) {
    return bubblebotJNI.Processor_processForm(swigCPtr, this, outPath);
  }

  public boolean writeFormImage(String outputPath) {
    return bubblebotJNI.Processor_writeFormImage(swigCPtr, this, outputPath);
  }

}
